name: eyetrack
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - jupyterlab
  - pip
  - pip:
      - opencv-python
      - mediapipe>=0.10.9
